name: build main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: use Node.js 20
        uses: actions/setup-node@v3.2.0
        with:
          node-version: '20'
      - run: npm ci
      - name: Build
        run: npm run build
